### ISSUE TITLE
🛠 Adjustments - Badge (iOS)

### ISSUE THREAD

**Issue by julianasouza-s** [ocean-ds/ocean-ios#212]
- Change the name Tiny to Dot and make it a badge subtype (like count or text), not a size option.
- Badge Text with Colors shouldn't exist
- Badge Text no longer exist as a badge, it will be a Tag variation. See Tag adjustments.

🔗 [Hand-off here.](https://www.figma.com/file/PgLv9k22CHHZZ867HwN65y/%E2%9D%96-Core-Components?node-id=9391%3A83667&t=8pzxmGLSNWMg3GR9-11)

**Comment by AcassioM** [comment]
issue done.
