### ISSUE TITLE
🛠 Adjustments - Tag (iOS)

### ISSUE THREAD

**Issue by julianasouza-s** [ocean-ds/ocean-ios#213]
- Remove `Neutral 02` Tag, we are not using it
- Change **Neutral 03** to `Complementary`
- Change **Neutral 01** to `Neutral`

- Add Tag Highlight (former Badge Text)

🔗 [Hand-off here.](https://www.figma.com/file/PgLv9k22CHHZZ867HwN65y/%E2%9D%96-Core-Components?node-id=3%3A62&t=8pzxmGLSNWMg3GR9-11)

**Comment by AcassioM** [comment]
Issue done.
